name: PubMed Agent

on:
  schedule:
    - cron: "0 11 * * *"  # roda todo dia às 10:00 no Brasil (~11:00 UTC)
  workflow_dispatch:  # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:                       # <<--- ADICIONE ESTA PARTE
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
        run: python main.py
